[package]
name = "lesson_12_4_wasm_wasm_bindgen"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "lesson_12_4_wasm_wasm_bindgen_benchmark"
harness = false
