[package]
name = "lesson_02_7_structs_with_references_lifetime_parameters"
version = "0.1.0"
edition = "2021"

[dependencies]


[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "lesson_02_7_structs_with_references_lifetime_parameters_benchmark"
harness = false
