[package]
name = "lesson_07_1_intro_to_async_await"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "lesson_07_1_intro_to_async_await_benchmark"
harness = false
