[package]
name = "lesson_18_5_benchmark_rust_vs_python_preprocessing"
version = "0.1.0"
edition = "2021"

[dependencies]


[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "lesson_18_5_benchmark_rust_vs_python_preprocessing_benchmark"
harness = false
