[package]
name = "lesson_10_5_graceful_shutdowns_with_select"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "lesson_10_5_graceful_shutdowns_with_select_benchmark"
harness = false
