[package]
name = "lesson_16_5_deploying_to_cloud_run_or_fly_io"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "lesson_16_5_deploying_to_cloud_run_or_fly_io_benchmark"
harness = false
