[package]
name = "lesson_12_1_pyo3_and_maturin_basics"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "lesson_12_1_pyo3_and_maturin_basics_benchmark"
harness = false
