[package]
name = "lesson_16_3_github_actions_ci_cd_pipeline"
version = "0.1.0"
edition = "2021"

[dependencies]


[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "lesson_16_3_github_actions_ci_cd_pipeline_benchmark"
harness = false
