[package]
name = "lesson_11_1_rc_arc_and_reference_counting"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "lesson_11_1_rc_arc_and_reference_counting_benchmark"
harness = false
