[package]
name = "lesson_08_2_select_and_graceful_shutdowns"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "lesson_08_2_select_and_graceful_shutdowns_benchmark"
harness = false
