[package]
name = "lesson_07_3_tokio_fundamentals"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "lesson_07_3_tokio_fundamentals_benchmark"
harness = false
