[package]
name = "lesson_09_1_mod_pub_and_use"
version = "0.1.0"
edition = "2021"

[dependencies]


[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "lesson_09_1_mod_pub_and_use_benchmark"
harness = false
