[package]
name = "lesson_03_3_enums_and_pattern_matching_mastery"
version = "0.1.0"
edition = "2021"

[dependencies]


[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "lesson_03_3_enums_and_pattern_matching_mastery_benchmark"
harness = false
