[package]
name = "lesson_05_2_custom_error_types"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "lesson_05_2_custom_error_types_benchmark"
harness = false
