[package]
name = "lesson_10_4_cpu_bound_work_with_spawn_blocking"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "lesson_10_4_cpu_bound_work_with_spawn_blocking_benchmark"
harness = false
