[package]
name = "lesson_04_1_defining_traits"
version = "0.1.0"
edition = "2021"

[dependencies]


[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "lesson_04_1_defining_traits_benchmark"
harness = false
