[package]
name = "lesson_18_3_parallel_tokenization_and_chunking"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "lesson_18_3_parallel_tokenization_and_chunking_benchmark"
harness = false
